spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=df536a4e-3386-4046-9c97-d8e41c89806d
spring.cloud.azure.active-directory.credential.client-id=ad0920b4-a99e-449b-8df0-6703cf2402ed
spring.cloud.azure.active-directory.app-id-uri=api://ad0920b4-a99e-449b-8df0-6703cf2402ed
server.port=8080